issues:
  exclude-use-default: false
linters:
  disable:
    - exhaustivestruct
    - goerr113
    - golint
    - interfacer
    - maligned
    - nlreturn
    - paralleltest
    - scopelint
    - wsl
  enable-all: true
linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Blob(
      - .HTML(
      - .NewHTTPError(
      - .String(
run:
  concurrency: 4
  timeout: 30s
